name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm i
      - run: npm run scully:build
